// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc5112.Robot2015;

import org.usfirst.frc5112.Robot2015.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.command.StartCommand;

import org.usfirst.frc5112.Robot2015.subsystems.*;

/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {

	public Joystick driveStick;
	public XboxController xbox;
	private JoystickButton button3, button4;

	public OI() {
		xbox = new XboxController(1);
		driveStick = new Joystick(0);

		xbox.LB.whenPressed(new CloseGripper());
		xbox.RB.whenPressed(new OpenGripper());
		xbox.LT.whileActive(new ElevatorDown(0.9));
		xbox.RT.whileActive(new ElevatorUp(0.9));
		xbox.START.whenPressed(new StopCompressor());
		xbox.BACK.whenPressed(new StartCompressor());
		xbox.DPAD_DOWN.whenActive(new DriveBackHumanPlayerStation());

		button3 = new JoystickButton(driveStick, 3);
		button4 = new JoystickButton(driveStick, 4);

		button3.whileHeld(new DriveLeft(0.8));
		button4.whileHeld(new DriveRight(0.8));

	}

	public Joystick getDriveStick() {
		return driveStick;
	}

	public XboxController getXbox() {
		return xbox;
	}

}
