// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc5112.Robot2015.subsystems;

import org.usfirst.frc5112.Robot2015.RobotMap;
import org.usfirst.frc5112.Robot2015.commands.*;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.Solenoid;

import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Gripper extends Subsystem {

	private final Solenoid gripperSolenoid = RobotMap.gripperGripperSolenoid;

	public void initDefaultCommand() {
	}

	public void close() {
		gripperSolenoid.set(true);
	}

	public void open() {
		gripperSolenoid.set(false);
	}

	public boolean isOpen() {
		return !gripperSolenoid.get();
	}

	public boolean isClosed() {
		return gripperSolenoid.get();
	}
}
